// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Sep 2019 17:18:43 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package memkind

/*
#cgo LDFLAGS: -lmemkind
#include "memkind.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"
import (
	"sync"
	"unsafe"
)

// Ref returns a reference to C object as it is.
func (x *MemkindConfig) Ref() *C.struct_memkind_config {
	if x == nil {
		return nil
	}
	return (*C.struct_memkind_config)(unsafe.Pointer(x))
}

// Free cleanups the referenced memory using C free.
func (x *MemkindConfig) Free() {
	if x != nil {
		C.free(unsafe.Pointer(x))
	}
}

// NewMemkindConfigRef converts the C object reference into a raw struct reference without wrapping.
func NewMemkindConfigRef(ref unsafe.Pointer) *MemkindConfig {
	return (*MemkindConfig)(ref)
}

// NewMemkindConfig allocates a new C object of this type and converts the reference into
// a raw struct reference without wrapping.
func NewMemkindConfig() *MemkindConfig {
	return (*MemkindConfig)(allocStructMemkindConfigMemory(1))
}

// allocStructMemkindConfigMemory allocates memory for type C.struct_memkind_config in C.
// The caller is responsible for freeing the this memory via C.free.
func allocStructMemkindConfigMemory(n int) unsafe.Pointer {
	mem, err := C.calloc(C.size_t(n), (C.size_t)(sizeOfStructMemkindConfigValue))
	if err != nil {
		panic("memory alloc error: " + err.Error())
	}
	return mem
}

const sizeOfStructMemkindConfigValue = unsafe.Sizeof([1]C.struct_memkind_config{})

// cgoAllocMap stores pointers to C allocated memory for future reference.
type cgoAllocMap struct {
	mux sync.RWMutex
	m   map[unsafe.Pointer]struct{}
}

var cgoAllocsUnknown = new(cgoAllocMap)

func (a *cgoAllocMap) Add(ptr unsafe.Pointer) {
	a.mux.Lock()
	if a.m == nil {
		a.m = make(map[unsafe.Pointer]struct{})
	}
	a.m[ptr] = struct{}{}
	a.mux.Unlock()
}

func (a *cgoAllocMap) IsEmpty() bool {
	a.mux.RLock()
	isEmpty := len(a.m) == 0
	a.mux.RUnlock()
	return isEmpty
}

func (a *cgoAllocMap) Borrow(b *cgoAllocMap) {
	if b == nil || b.IsEmpty() {
		return
	}
	b.mux.Lock()
	a.mux.Lock()
	for ptr := range b.m {
		if a.m == nil {
			a.m = make(map[unsafe.Pointer]struct{})
		}
		a.m[ptr] = struct{}{}
		delete(b.m, ptr)
	}
	a.mux.Unlock()
	b.mux.Unlock()
}

func (a *cgoAllocMap) Free() {
	a.mux.Lock()
	for ptr := range a.m {
		C.free(ptr)
		delete(a.m, ptr)
	}
	a.mux.Unlock()
}

// PassRef returns a reference to C object as it is or allocates a new C object of this type.
func (x *MemkindConfig) PassRef() *C.struct_memkind_config {
	if x == nil {
		x = (*MemkindConfig)(allocStructMemkindConfigMemory(1))
	}
	return (*C.struct_memkind_config)(unsafe.Pointer(x))
}

type sliceHeader struct {
	Data unsafe.Pointer
	Len  int
	Cap  int
}

// safeString ensures that the string is NULL-terminated, a NULL-terminated copy is created otherwise.
func safeString(str string) string {
	if len(str) > 0 && str[len(str)-1] != '\x00' {
		str = str + "\x00"
	} else if len(str) == 0 {
		str = "\x00"
	}
	return str
}

// unpackPCharString represents the data from Go string as *C.char and avoids copying.
func unpackPCharString(str string) (*C.char, *cgoAllocMap) {
	str = safeString(str)
	h := (*stringHeader)(unsafe.Pointer(&str))
	return (*C.char)(h.Data), cgoAllocsUnknown
}

type stringHeader struct {
	Data unsafe.Pointer
	Len  int
}
