// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Sep 2019 17:18:43 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

#include "memkind.h"
#include <stdlib.h>
#pragma once

#define __CGOGEN 1

