// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Sep 2019 17:18:43 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package memkind

/*
#cgo LDFLAGS: -lmemkind
#include "memkind.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// MemkindMemtypeT as declared in https://google.com/search?q=memkind.h+memkind_memtype_t
type MemkindMemtypeT int32

// MemkindMemtypeT enumeration from https://google.com/search?q=memkind.h+memkind_memtype_t
const ()

// MemkindPolicyT as declared in https://google.com/search?q=memkind.h+memkind_policy_t
type MemkindPolicyT int32

// MemkindPolicyT enumeration from https://google.com/search?q=memkind.h+memkind_policy_t
const ()

// MemkindBitsT as declared in https://google.com/search?q=memkind.h+memkind_bits_t
type MemkindBitsT int32

// MemkindBitsT enumeration from https://google.com/search?q=memkind.h+memkind_bits_t
const ()

// MemkindConst as declared in memkind/memkind.h;memkind.h;124;;;
type MemkindConst int32

// MemkindConst enumeration from memkind/memkind.h;memkind.h;124;;;
const ()

// MemkindMemUsagePolicy as declared in https://google.com/search?q=memkind.h+memkind_mem_usage_policy
type MemkindMemUsagePolicy int32

// MemkindMemUsagePolicy enumeration from https://google.com/search?q=memkind.h+memkind_mem_usage_policy
const ()

const ()
