// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Sep 2019 18:50:42 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

/*
Package memkind provides Go bindings for mekind implementation
*/
package memkind
