// THE AUTOGENERATED LICENSE. ALL THE RIGHTS ARE RESERVED BY ROBOTS.

// WARNING: This file has automatically been generated on Tue, 10 Sep 2019 18:50:42 CST.
// Code generated by https://git.io/c-for-go. DO NOT EDIT.

package memkind

/*
#cgo LDFLAGS: -lmemkind
#include "memkind.h"
#include <stdlib.h>
#include "cgo_helpers.h"
*/
import "C"

// MemkindT as declared in https://google.com/search?q=memkind.h+memkind_t
type MemkindT C.memkind_t

// MemkindConfig as declared in https://google.com/search?q=memkind.h+memkind_config
type MemkindConfig C.struct_memkind_config
